"""add_analysts_activities_alert_assignment

Revision ID: 3659a7c69cf1
Revises: 0e2498886fc2
Create Date: 2026-03-13 11:42:34.756632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3659a7c69cf1'
down_revision: Union[str, Sequence[str], None] = '0e2498886fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysts',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysts')),
    sa.UniqueConstraint('username', name=op.f('uq_analysts_username'))
    )
    op.create_table('activities',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('analyst_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyst_username', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_activities_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['analyst_id'], ['analysts.id'], name=op.f('fk_activities_analyst_id_analysts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_alert_id'), 'activities', ['alert_id'], unique=False)
    op.add_column('alerts', sa.Column('assigned_to', sa.Uuid(), nullable=True))
    op.add_column('alerts', sa.Column('assigned_username', sa.String(length=100), nullable=True))
    op.create_foreign_key(op.f('fk_alerts_assigned_to_analysts'), 'alerts', 'analysts', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_alerts_assigned_to_analysts'), 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'assigned_username')
    op.drop_column('alerts', 'assigned_to')
    op.drop_index(op.f('ix_activities_alert_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('analysts')
    # ### end Alembic commands ###
