"""add_alert_duplicate_count

Revision ID: e4ae68da1d53
Revises: 3659a7c69cf1
Create Date: 2026-03-13 12:30:10.099679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ae68da1d53'
down_revision: Union[str, Sequence[str], None] = '3659a7c69cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('duplicate_count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'duplicate_count')
    # ### end Alembic commands ###
