apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
{{ include "opensoar.labels" . | indent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/component: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
{{ include "opensoar.labels" . | indent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
{{ include "opensoar.labels" . | indent 8 }}
        app.kubernetes.io/component: ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}"
          imagePullPolicy: {{ .Values.images.ui.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
